# Site settings
title: Секреты управления жизнью
subtitle: Знания. Вещи. Технологии
author: Дмитрий Калинников
email: dmitry@kalinnikov.ru
description: > # this means to ignore newlines until "baseurl:"
  Бортовой журнал, дворец памяти, knowledge management, 
  избавление от ненужных вещей, рассуждения на вольные темы
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kalinnikov.ru" # the base hostname & protocol for your site
twitter_username: beeos
github_username:  beeos

# Build settings
markdown: kramdown